#!/usr/bin/env node

/**
 * Install git hooks for code graph refresh.
 * Called during `npm prepare` (after npm install or npm ci).
 * Silently succeeds even if .git is unavailable (e.g., in a tarball export).
 */

import { writeFileSync, mkdirSync, chmodSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const cwd = join(__dirname, "..");

const hookPath = join(cwd, ".git", "hooks", "post-commit");

// Try to create the hooks directory if it doesn't exist
try {
  mkdirSync(join(cwd, ".git", "hooks"), { recursive: true });
} catch {
  // .git might not exist in certain environments (exports, CI), skip silently
  process.exit(0);
}

// Create the post-commit hook: call the refresh script and ignore failures
const hookContent = `#!/bin/sh
# Auto-generated by scripts/install-hooks.mjs
# Refresh the code graph after commit (if graphify is available).
# Always exit 0 (never blocks a commit).

node "${join(cwd, "scripts", "refresh-code-graph.mjs")}" || true
exit 0
`;

try {
  writeFileSync(hookPath, hookContent);
  chmodSync(hookPath, 0o755); // Make it executable
} catch {
  // If we can't write the hook, fail silently. The check-drift channel will
  // just see a missing graph and skip using it.
  process.exit(0);
}
