#!/usr/bin/env node

/**
 * Install the post-commit hook that refreshes the code graph.
 *
 * Runs from `npm prepare`, so a plain `npm install` wires it -- the deeper
 * arrow check is on by default, with a cheap guard, never opt-in.
 *
 * Careful where it must be: a hook file we did not generate is somebody
 * else's and is left alone. No .git directory (a tarball export, a linked
 * worktree where .git is a file) means no hook, silently -- the checker then
 * simply sees no graph.
 */

import { chmodSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const MARKER = "generated by scripts/install-hooks.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const hooksDir = join(root, ".git", "hooks");
const hookPath = join(hooksDir, "post-commit");

// Git hooks run with the repo root as the working directory, so the script is
// named relatively and the hook survives the checkout being moved.
const hookContent = `#!/bin/sh
# ${MARKER} -- refreshes the code graph after each commit.
# Quiet and optional: it never blocks or fails a commit.
node scripts/refresh-code-graph.mjs || true
exit 0
`;

try {
  if (!existsSync(hooksDir)) process.exit(0);
  if (existsSync(hookPath) && !readFileSync(hookPath, "utf8").includes(MARKER)) {
    // Somebody's own hook. Leaving it alone beats silently replacing it.
    process.exit(0);
  }
  writeFileSync(hookPath, hookContent);
  chmodSync(hookPath, 0o755);
} catch {
  // Nothing here may ever fail an npm install.
}
process.exit(0);
